# -*- coding: utf-8 -*-
"""Day5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RpVthO9lx7l-ffynVennNx0PQplN4AzT
"""

# print("Mengitung Dari 5 ke 0")
# for i in range(5, 0, -1):
#   print(i)
# print("Menghitung dari 0 ke 5")
# count = 0
# while count <= 5:
#   print(count)
#   count += 1
# import time

# Countdown Timer

import time

# Step 1: Get user input for countdown start
start = int(input("Enter the number to start the countdown from: "))

# Step 2: Countdown using a while loop
print("\n--- Countdown Begins ---")
while start > 0:
  print(start)
  time.sleep(1)
  start -= 1

# Step 3: Print final message
print("Countdown Complete!")